apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: backend-secret
  namespace: nudge

spec:
  refreshInterval: 1h

  secretStoreRef:
    name: aws-secret-store
    kind: SecretStore

  target:
    name: backend-secret

  data:
    - secretKey: DB_USER
      remoteRef:
        key: nudge/backend
        property: DB_USER

    - secretKey: DB_PASSWORD
      remoteRef:
        key: nudge/backend
        property: DB_PASSWORD

    - secretKey: DB_NAME
      remoteRef:
        key: nudge/backend
        property: DB_NAME